CREATE USER 'arthur' IDENTIFIED BY 'arthur123';
CREATE USER 'maximes' IDENTIFIED BY 'maxime123';
CREATE USER 'maximef' IDENTIFIED BY 'maxime123';
CREATE USER 'titouan' IDENTIFIED BY 'titouan123';

GRANT ALL PRIVILEGES ON *.* TO 'arthur' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'maximes' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'maximef' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'titouan' WITH GRANT OPTION;